### ISSUE TITLE
Oracle connector

### ISSUE THREAD

**Issue by Philippe-M** [biblibre/urungi#15] opened 2019-03-14 15:34 UTC
when I select Oracle mode as the data source. I enter the information requested by the form and when I click on the connection test button I have the message :

`Error executing test connection SQL : TypeError: "listener" argument must be a function`

On the urungi server I installed node-oracle and installed the oracle basic client

**Comment by jajm** [comment] 2019-03-15 09:02
Hi,

I do not have access to an Oracle database so I can't really test this, but I can reproduce the error message and tried to fix it in branch `fix-oracle-connection`.
Can you retry using this branch ?

**Comment by Philippe-M** [comment] 2019-03-15 11:16
I just did the test with the fix-oracle-connection branch and it's better but when I set the data source and test the connection I get the message:

Error executing test connection SQL : Error: select "owner", "table_name", "column_name", "data_type" from "user_tab_columns" - ORA-00942: table or view does not exist

I test from the urungi server to connect with sqlplus and everything is ok.

**Comment by Philippe-M** [comment] 2019-03-18 08:58
I think the problem is that my tables contain prefixes and are not supported in urungi

**Comment by jajm** [comment] 2019-03-18 09:08
I'm not familiar with Oracle, but it looks like it's a permission problem.
user_tab_columns table should be there but maybe your user doesn't have access to it ?

**Comment by Philippe-M** [comment] 2019-03-18 09:10
If I reproduce the query with sqlplus I have 

```
# sqlplus MYUSER/MYPWD
SQL> select table_name from sys.all_tables where owner = 'MYUSER';
no rows selected
```

But if I make the same query without specifying owner:

```
# sqlplus MYUSER/MYPWD
SQL> select table_name from sys.all_tables;
```

The list of tables to which this user has access appears.

**Comment by PaulPoulain** [comment] 2019-03-20 10:19
FYI : next week, 2 developers from AFI are coming to work with us on Urungi. Their goal is to use Urungi for 2 software that use Oracle as DB. So we will fix the problem, for sure !
@Philippe-M which Oracle version are you using ?

**Comment by Philippe-M** [comment] 2019-03-20 10:49
That's very good news.

@PaulPoulain I use Oracle 10

**Comment by jajm** [comment] 2019-03-28 10:37
@Philippe-M I added a new commit to the `fix-oracle-connection` branch. It worked for us. Can you retry ?

**Comment by jajm** [comment] 2019-04-08 09:38
Merged `fix-oracle-connection` into `master` 

https://github.com/biblibre/urungi/commit/c97f851adf3492462a532e6777846bfce9de18e6

**Closed by jajm** 2019-04-08 09:38 UTC
