### ISSUE TITLE
how to extend oracle database schema fields like 'DATA_LENGTH', 'DATA_PRECISION', 'NULLABLE', 'DATA_DEFAULT' 

### ISSUE THREAD

**Issue by helxsz** [biblibre/urungi#153] opened 2019-10-15 01:11 UTC
I looked into the code on [urungi/server/core/connection.js](https://github.com/biblibre/urungi/blob/df511b4463aa931b5a93b06677587ddb5f5ff09b/server/core/connection.js)

```
    case 'ORACLE':
        query = (knex) =>
            knex.select({ table_schema: knex.raw('user') }, { table_name: 'TABLE_NAME' }, { column_name: 'COLUMN_NAME' }, { data_type: knex.raw('LOWER(data_type)') })
                .from('USER_TAB_COLUMNS')
                .where('TABLE_NAME', collection.name)
                .orderBy('COLUMN_NAME');
        break;
```
The code could return the database schema with 4 fields 'table_schema', 'table_name', 'column_name', 'data_type'.  I need to extend this to other fields like 'DATA_LENGTH', 'DATA_PRECISION', 'NULLABLE', 'DATA_DEFAULT'.

P.S. I don't know why the code of fetching oracle schema is so different from other database.

For example, 

for other db like POSTGRESQL
```
    case 'POSTGRESQL':
            knex.select('table_schema', 'table_name', 'column_name', 'data_type','is_nullable','character_maximum_length','numeric_precision','is_identity','table_catalog')
```

for oracle db
```
    case 'ORACLE':
            knex.select({ table_schema: knex.raw('user') }, { table_name: 'TABLE_NAME' }, { column_name: 'COLUMN_NAME' }, { data_type: knex.raw('LOWER(data_type)') })
```

just wonder why oracle 's code is coding like that ? 

if I want to extend oracle schema fields like 'DATA_LENGTH', 'DATA_PRECISION', 'NULLABLE', 'DATA_DEFAULT'. 
how to exactly do it ?

**Comment by jajm** [comment] 2019-10-15 07:33
> just wonder why oracle 's code is coding like that ?

It has something to do with how Oracle handle character case

```
SELECT "table_name" FROM "USER_TAB_COLUMNS"
```

doesn't work because the column name should be in upper case

```
SELECT "TABLE_NAME" FROM "USER_TAB_COLUMNS"
```

As for the odd `{table_name: 'TABLE_NAME'}` syntax, it's just the knex syntax for specifying column aliases

So we end up with a query similar to this

```
SELECT "TABLE_NAME" "table_name" FROM "USER_TAB_COLUMNS";
```

And it's easier to handle the results in the code because all columns have the same name and case, no matter which RDBMS we queried

> 
> if I want to extend oracle schema fields like 'DATA_LENGTH', 'DATA_PRECISION', 'NULLABLE', 'DATA_DEFAULT'.
> how to exactly do it ?

Just like the other columns.

Out of curiosity, why do you want these schema fields ?

**Comment by helxsz** [comment] 2019-10-15 09:10
Thanks @jajm 

because i want to extract all the necessary schema and use these schema to create a same table in another database.

```
   Column    |            Type             |                       Modifiers
-------------+-----------------------------+--------------------------------------------------------
 city_id     | integer                     | not null default nextval('city_city_id_seq'::regclass)
 city        | character varying(50)       | not null
 country_id  | smallint                    | not null
 last_update | timestamp without time zone | not null default now()
Indexes:
    "city_pkey" PRIMARY KEY, btree (city_id)
    "idx_fk_country_id" btree (country_id)
Foreign-key constraints:
    "fk_city" FOREIGN KEY (country_id) REFERENCES country(country_id)
Referenced by:
    TABLE "address" CONSTRAINT "fk_address_city" FOREIGN KEY (city_id) REFERENCES city(city_id)
Triggers:
    last_updated BEFORE UPDATE ON city FOR EACH ROW EXECUTE PROCEDURE 
```

right now, if I am merely using the column info, would I be able to tell the primary Id of the table . 

 a further question is how would I do to extract Indexes,Foreign-key constraints ,Referenced by ?

**Comment by jajm** [comment] 2019-10-15 09:15
> because i want to extract all the necessary schema and use these schema to create a same table in another database.

Hmm... Are you sure Urungi is the right tool for this task ?

> right now, if I am merely using the column info, would I be able to tell the primary Id of the table .
> a further question is how would I do to extract Indexes,Foreign-key constraints ,Referenced by ?

It depends on the RDBMS you are using, and I am not familiar with Oracle, so I can't answer that

**Comment by helxsz** [comment] 2019-10-15 10:08
I would use the postgresql for the tests, I look at the https://www.postgresql.org/docs/current/infoschema-referential-constraints.html, probably it is the answer, i will try it out to see the relationships between the tables

**Comment by jajm** [comment] 2019-10-24 12:09
Closing as it is not a bug report nor a feature request

**Closed by jajm** 2019-10-24 12:09 UTC
Labels: enhancement
