### ISSUE TITLE
impossible to delete user

### ISSUE THREAD

**Issue by ldsbiblibre** [biblibre/urungi#217] opened 2019-12-12 14:51 UTC
**Description**
when i create a user in urungi i cant delete it

**To Reproduce**
1. Go to urungi
2. Click on user
3. create user
4. no possibility to delete user

**Expected behavior**
please add a function to delete user

**Server (please complete the following information):**
 - OS: [e.g. ubuntu xenial]
 - NodeJS: [v12.13.1]
 - MongoDB: v4.2.1]
 - Datasource(s): [MariaDB 10.0]

**Comment by jajm** [comment] 2020-01-17 16:01
Duplicate of #201

**Closed by jajm** 2020-01-17 16:01 UTC
Labels: bug
